routes:
  - path: /
    destination: /index.html
  - path: /scoreboard
    destination: /index.html
  - path: /scoreboard/*
    destination: /index.html
  - path: /mesario/*
    destination: /index.html
  - path: /lateral/*
    destination: /index.html
  - path: /admin
    destination: /index.html
  - path: /perfil
    destination: /index.html
  - path: /configuracoes
    destination: /index.html
  - path: /cadastro
    destination: /index.html
  - path: /login
    destination: /index.html
  - path: /<path>
    destination: /index.html
