services:
  - type: web
    name: omegateam-frontend
    env: node
    buildCommand: bash render-build.sh
    startCommand: npm start
    preDeployCommand: npm install
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        value: https://omegateam-backend.onrender.com
